curve/tool: basic framework
1. It can be used like this:
$ curve fs list fs
Name    Id  Status  Type    MountNum
test_1  1   INITED  TYPE_S3 1
test_2  2   INITED  TYPE_S3 1
$ curve fs list fs --format json
{
    "error":{
	"code":0,
	"message": "sucess",
    },
    "detail":{
        "fsInfo":[
            {
                "fsId":2,
                "fsName":"test_2",
                "status":"INITED",
                "rootInodeId":"1",
                "capacity":"18446744073709551615",
                "blockSize":"1048576",
                "mountNum":1,
                "mountpoints":[
                    "localhost:9004:/curvefs/client/mnt/home/nbs/temp/mnt2"
                ],
                "fsType":"TYPE_S3",
                "detail":{
                    "s3Info":{
                        "ak":"minioadmin",
                        "sk":"minioadmin",
                        "endpoint":"http://172.17.0.2:9000",
                        "bucketname":"test",
                        "blockSize":"4194304",
                        "chunkSize":"67108864"
                    }
                },
                "enableSumInDir":false
            },
            {
                "fsId":1,
                "fsName":"test_1",
                "status":"INITED",
                "rootInodeId":"1",
                "capacity":"18446744073709551615",
                "blockSize":"1048576",
                "mountNum":1,
                "mountpoints":[
                    "localhost:9002:/curvefs/client/mnt/home/nbs/temp/mnt1"
                ],
                "fsType":"TYPE_S3",
                "detail":{
                    "s3Info":{
                        "ak":"minioadmin",
                        "sk":"minioadmin",
                        "endpoint":"http://172.17.0.2:9000",
                        "bucketname":"test",
                        "blockSize":"4194304",
                        "chunkSize":"67108864"
                    }
                },
                "enableSumInDir":false
            }
        ]
    }
}

If the command entered is incomplete:
$ curve fs
Usage:  curve COMMAND [OPTIONS]

curve is a tool for managing curvefs ands curvebs

Commands:
  fs          Manage curve fs cluster

Options:
  -f, --format string   Output format(json|plain)
  -h, --help            Print usage
  -v, --version         Print curve version

Run 'curve COMMAND --help' for more information on a command.

2. If the command entered is not supported:
$ curve ds
Error: unknown command "ds" for "curve"

Did you mean this?
        fs

Run 'curve --help' for usage.

3. If the input flag is not supported:
$ curve fs --error
Error: unknown flag: --error
See 'curve fs --help'

4. Want to know how the command is used:
$ curve fs --help
Usage:  curve COMMAND [OPTIONS]

curve is a tool for managing curvefs ands curvebs

Commands:
  fs          Manage curve fs cluster

Options:
  -f, --format string   Output format(json|plain)
  -h, --help            Print usage
  -v, --version         Print curve version

Run 'curve COMMAND --help' for more information on a command.